.PHONY: all
all:

.PHONY: clean
clean:
	make -C VecAdd clean
	make -C Histogram clean
	make -C Transpose clean
	make -C Reduce clean
	make -C Scan clean
	make -C MatVecMul clean
	make -C MatMul clean
	make -C BitonicSortSmall clean
	make -C BitonicSortLarge clean
	make -C SparseMatVecMul clean
	make -C FastZeroEval clean