[package]
name = "nocl"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv-rt = "0.11.0"
linked_list_allocator = "0.10.5"

[profile.release]
debug = true

[features]
large_data_set = []
disable_bounds_checks = []
