name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-with-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: "true"

    # -----------
    # Build SIMTight 
    # -----------
    
    - name: Get dependences 
      run: |
          sudo apt-get update
          sudo apt-get install apt-utils -y

          # Install basic packages
          sudo apt-get install -y verilator gcc-riscv64-unknown-elf \
                                  libgmp-dev python3 python3-pip g++\
                                  clang llvm lld clang-tidy clang-format \
                                  gcc-multilib gcc cmake sudo wget vim \
                                  curl tmux git bc

          # Install cheribuild dependencies 
          sudo apt-get install -y autoconf automake libtool pkg-config \
                                  clang bison cmake mercurial ninja-build \
                                  samba flex texinfo time libglib2.0-dev \
                                  libpixman-1-dev libarchive-dev libarchive-tools \
                                  libbz2-dev libattr1-dev libcap-ng-dev \
                                  libexpat1-dev libgmp-dev

          pip3 install --user --upgrade pip
          pip3 install black colorlog toml tabulate isort

    - name: Install GHC 
      run: |
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | \
             BOOTSTRAP_HASKELL_NONINTERACTIVE=1 \
             BOOTSTRAP_HASKELL_GHC_VERSION=latest \
             BOOTSTRAP_HASKELL_CABAL_VERSION=latest \
             BOOTSTRAP_HASKELL_INSTALL_STACK=1 \
             BOOTSTRAP_HASKELL_INSTALL_HLS=1 \
             BOOTSTRAP_HASKELL_ADJUST_BASHRC=P sh

    - name: Build cheri-llvm 
      run: |
          bash scripts/build-cheri.sh

