.PHONY: clean
clean:
	make -C HelloWorld clean
	make -C TestSuite clean
	make -C VecAdd clean
	make -C VecGCD clean
	make -C Histogram clean
	make -C Transpose clean
	make -C Reduce clean
	make -C Scan clean
	make -C MatVecMul clean
	make -C MatMul clean
	make -C StripedStencil1 clean
	make -C StripedStencil2 clean
